### ISSUE TITLE
How to load textues?

### ISSUE THREAD

**Issue by JamesO2x** [X-Hax/SonicAdventureBlenderIO#1]
Upon import, the model is solid black. How can I load textures into the model? Do I have to load the *tex.prs file directly, or do I have to split that into pngs or something?

EDIT: Ah, I figured it out. You have to load the textures PRS file before importing the model. I'm sure there's a way to load textures after a model is imported, but it's not exactly clear to me how that works. I read the Wiki, but couldn't really understand how the texture system works - its  a very different workflow from how Blender normally sets up materials.

I'm gonna leave this issue open because I still don't fully understand the process. I think a more clear explanation of how to load and modify textures on the fly would be helpful.

**Comment by Justin113D** [comment]
Please read the documentation on workflow issues
https://x-hax.github.io/SonicAdventureBlenderIODocs/guides/texturing/#updating-textures-on-materials
