### ISSUE TITLE
Loading models from SA Tools project on Blender 4.1

### ISSUE THREAD

**Issue by ken-foster** [X-Hax/SonicAdventureBlenderIO#12]
On Blender 4.1 (installed through Steam), attempting to import any model from an SA Tools project results in the error screenshotted below:

![image](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/38412483/29f94ed8-506b-4dc2-84e3-44a978852137)

Reverting to Blender 4.0.2 by installing through the .msi file downloaded from Blender's website solves the issue.

I love this tool, by the way. You're opening up modding to people who never would have dreamed of attempting it!

**Comment by GegaleFox** [comment]
i also experienced this error while modding lol

**Comment by NostalgiaNinja** [comment]
Blender 4.1 changes how smooth shading works through auto shade smooth. The function call was removed in favor of the new smoothing methods. The plugin will need to be updated.

**Comment by Justin113D** [comment]
Issue has been fixed with 2.1.5.
