### ISSUE TITLE
Scene Link Failure

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SonicAdventureBlenderIO#17]
Blender has a small issues where it does not proactively remove linked libraries when it's running. As a result it's possible to end up in a situation where you cannot properly edit materials. 

This often happens when performing a data cleanup (it's not consistent which may be more of a Blender issue) when nothing is actively using the SAShader. It ends up removed, but the library isn't unlinked. This causes users to be unable to work with the SAShader properly.

Best ways to fix this seem to be one of two options; first is to link the Scene from the blend file it's stored in. The other is to alter the check for linking the data to still attempt to import from the linked library even if it's found to still be loaded instead of not going through the linking process if the linked library is found.

**Comment by Justin113D** [comment]
Adjusted in release 2.2.0
