### ISSUE TITLE
SA2B landtable crash at adress 41cb2b

### ISSUE THREAD

**Issue by Chao-Chap** [X-Hax/SonicAdventureBlenderIO#19]
I have been attempting to import a landtable to sa2. But when i import it, i get this error, I am told this is crash inside the ginja model renderer, and that it is a nullptr crash, and was told i should ask here.
[pls.zip](https://github.com/user-attachments/files/16028231/pls.zip)

**Comment by Justin113D** [comment]
Can you provide a mod setup with which i can test the model?

**Comment by Justin113D** [comment]
After testing with https://github.com/Justin113D/Sa2CustomGarden, i got it to work no problem. This means that the crash was caused by the MyLevelMod, and not SAIO
