### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by DavoDav** [X-Hax/SonicAdventureBlenderIO#2]
<img width="1246" alt="Screen Shot 2023-10-04 at 5 29 25 PM" src="https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94305151/78883789-78d0-4c84-8262-72c1e8edfd98">

Hey there! So I tried to install the addon and it gave me this message when I tried to import a model. I don't know what I did wrong. I installed NET 7, I used blender 3.6, I'm not sure. If there's anyway you can help, I would very much appreciate that.

**Comment by dqf318** [comment]
I'm having the exact same issue. The NET version I have is 7.0.2.

**Comment by Justin113D** [comment]
You guys downloaded the addon via the download-repository button, which won't work here. You can see that your addon foldername ends with "-main", which it should not.

Download the addon from the releases section and it will work.

Sorry for the late response, i only now figured out that this error occurs whenever somebody installed via repo downloads. This will not be an issue in future releases.
