### ISSUE TITLE
Normals Issue

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SonicAdventureBlenderIO#21]
This is one is an odd bug, and it may be more Blender related than addon related, but it's something that needs to be looked into for potential solutions.

In short, importing exports from the old addon will show flipped normals in a lot of instances due to issues with the old addon not properly accounting for the normals error. Fixing them in Blender and re-exporting **does not** fix the issue with the models however. That's becoming a problem due to Render Fix enabling Backface Culling in SA2, and it's making it difficult to fix older exports using the new addon in the event the original blend file is lost/unable to be used.

All of the following images use [this model](https://github.com/user-attachments/files/16116444/reference-models.zip)
![Broken Import](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/8052134/3c14d4c1-b9ed-49e0-b003-0cba9a9b9cf3)
![Fixed Import](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/8052134/20a11bc3-6c01-4347-878a-97f4b3260181)

The first image is the initial import of the model (which is an exported model from the old addon) with the broken normals visible. The second image is the normals showing as fixed. This required both flipping the normals and clearing the `Custom Split Normals Data`. The fixed version was then exported and re-imported which resulted in the following image.

![Imported Result from Exporting the Fixed normals](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/8052134/9f97418c-12b3-42ab-9e64-dc0ad2699860)

As shown, fixing the normals and re-exporting doesn't actually fix this. I'm not sure what the cause is, as this appears to also be inducing an additional amount of flipped normals when exporting as shown by set of flipped normals being fixed in the front, but a new set of flipped normals being visible on the side of the model.

As I said, I'm not sure if this is more of a Blender bug or an addon bug, but it's indicating that the addon does need to make some adjustments in how it handles normals for export.

**Comment by Justin113D** [comment]
Fixed in release 2.2.0
