### ISSUE TITLE
SA2 Event Importing: Incorrect triangles

### ISSUE THREAD

**Issue by Marswastakenwastaken** [X-Hax/SonicAdventureBlenderIO#22]
# Issue
When importing an event, certain objects will have their vertices erroneously connected, which leads to them looking bugged.
Below are six images detailing what the issue looks like and how the objects should usually look. 

## e0002
![RadioError](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/d59a4317-4793-4b2c-8ef8-d47122637812)
![RadioProper](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/3fe2e64d-f8fa-4b63-bed6-fe8e7e799660)

## e0361
![BridgeError](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/1c1705dd-fc43-4678-8a44-c295aa62a044)
![BridgeProper](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/c52ed9f4-0d1b-4470-80ff-5e5846edd7f9)
(this error applies to any other event the model appears in)

## e0027
![ARKError](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/e43e72c1-cd3a-4e8a-b43f-e1695c53885f)
![ARKProper](https://github.com/X-Hax/SonicAdventureBlenderIO/assets/94758802/6b237f20-73bd-44c7-82dc-a721778a4752)
(this error applies to any other event the model appears in)

**Comment by Justin113D** [comment]
Fixed in release 2.2.0
