### ISSUE TITLE
Chunk - Remove 'Write Specular' Export Flag

### ISSUE THREAD

**Issue by shaddatic** [X-Hax/SonicAdventureBlenderIO#24]
This export flag was implimented under the assumption that SA2DC never used specular, and so is off by default. In reality, SA2DC used specular everywhere; meaning this flag strips specular information from models that actively use it causing models to look quite different after exporting. Many models in the PC version also have specular information as 95% of models remain unchanged from the Dreamcast version, although it can't be rendered in-game atm - and we should avoid another "old models are just broken like that" situation for when specular is restored.

While a good solution is to set this export flag to default on, I think a better solution is to remove it entirely as no other material property has an export flag like this. If there's concern about people making new models with specular accidentally on, perhaps make the 'Ignore Specular' Chunk flag on by default for new materials.

**Comment by Justin113D** [comment]
Fixed in release 2.2.0
