### ISSUE TITLE
SA2 Event Exporting: Bloated Motion files

### ISSUE THREAD

**Issue by Marswastakenwastaken** [X-Hax/SonicAdventureBlenderIO#25]
### Issue
In certain cutscenes, there is an issue where exporting the cutscene will produce a motion file much larger than that of the original.
![e0021sizebloat](https://github.com/user-attachments/assets/6d5e160e-6f9f-4d0f-aa78-117f8ce48a28)
![e0025sizebloat](https://github.com/user-attachments/assets/cbd94ff4-b9af-47c9-8df5-9fc00d6967cb)
**Files marked with `_og` are the original, unmodified files for comparison.**

This causes issues to arise when trying to play back the cutscenes in game.

This is what happens when I tried to play back an exported E0025. The camera seems to be locked to the origin at an angle.
![20240802161813_1](https://github.com/user-attachments/assets/c962c5b1-1a41-41c9-8341-8e5c6d6bd151)
**This issue also occurs for E0128 and E0210.**

When trying to play back an exported E0021, the game crashes at `48fc6f` when trying to load the motion file.
![e0021crashlog](https://github.com/user-attachments/assets/df1770a4-d915-4863-b9bf-9cddffe30040)
**This issue also occurs for E0111, E0120, E0124, and E0129.**

`Reporting on the current release version of the addon.`

**Comment by Justin113D** [comment]
The "bloat" is unfortunately not avoidable... when using the default export options, that is.
To prevent several other issues, by default, blender bakes out every single keyframe (where necessary), which bloats up the files tremendously. You can improve this by fiddling around with the advanced animation export options

**Comment by Marswastakenwastaken** [comment]
This will help tremendously. I just tested it, and while it looked a little weird due to not having good enough values, it ended up working with no issue! Thank you.

**Comment by Justin113D** [comment]
I just tested the crashes, and it seems that, if a motion.bin file is too large, the game recognizes animations further into the file as byteswapped and crashes... so the solution to that is to use the advanced settings too.

The usage of these is detailed in the guides: https://x-hax.github.io/SonicAdventureBlenderIO/ui/toolbar/tools/export/
The Test Bake tool helps you pre-visualize how certain animations would look ingame: https://x-hax.github.io/SonicAdventureBlenderIO/ui/toolbar/tools/utilities/#bake-node-animation

**Comment by Justin113D** [comment]
Somehow, the camera issue also relates to the advanced settings. Exporting with optimizations and thresholds fixes the issue...

**Comment by Justin113D** [comment]
I can't find the culprit for this exact issue when comparing the files either, so it must be a filesize issue too. Maybe one day we'll figure out why SA2 is like this and fix it, but for now, i'll call this case closed, as i cannot really do anything within SAIO to fix this
