### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by dqf318** [X-Hax/SonicAdventureBlenderIO#28]
With the new update, whenever I try to import a model, I get this error:
![image](https://github.com/user-attachments/assets/2cdd3f33-33be-40ac-bcb2-f79f3cc00e68)

**Comment by Justin113D** [comment]
Do you have NET 8.0 installed? https://x-hax.github.io/SonicAdventureBlenderIO/guides/installation/#installing-net-8

**Comment by Justin113D** [comment]
This was confirmed as the issue and has been resolved
