### ISSUE TITLE
Can you import assets into Blender & then Godot?

### ISSUE THREAD

**Issue by SengokuBasaraCP** [X-Hax/SonicAdventureBlenderIO#29]
I've been messing around with SATools and Blender.

I've installed Sonic Adventure I/O on Blender & I can make the textures pop-up for SonicvsShadow1. But whenever I export it from Blender as an object the textures don't load whenever I port it into Godot.  I've tried exporting with Materials & PBR items checked by the new obj just causes Godot to crash.

Also I am new to Blender too.

**Comment by Justin113D** [comment]
In order for an exporter to recognize material and texture setups, you need to enable the "principled material" setting of SAIO: https://x-hax.github.io/SonicAdventureBlenderIO/ui/scene/settings/#use-principled-bsdf
Note that depending on the exporter, this may not work, although GLTF (the recommended exporter for Godot) does support it.

**Comment by Justin113D** [comment]
I assume you are talking about the collision geometry, which is not visible in the actual game and often perfectly overlaps with the visible models, which causes the game to not know which of the models gets rendered first. 

Easiest would be to just hide the collision geometry in godot, or not export them in the first place (they are imported in a separate collection, so hiding or deleting them in blender shouldn't be too difficult)
![image](https://github.com/user-attachments/assets/4d08366b-075d-4b49-af3e-c41e1cfec6d9)

**Comment by SengokuBasaraCP** [comment]
Thank you so much! And I guess one more question is if it is possible for me to add animations to certain models in Blender?

Like the Sonic Model has a separate model/animation from its jumpball. And I was wondering if I could add the jumpball animation to the base Sonic model and delete the jumpball model too.

**Comment by SengokuBasaraCP** [comment]
Okay great!
Alright maybe one final question is do you one where the normal ring textures are located in the SA2 files? 
As it's not under the common objects texture.

**Comment by Justin113D** [comment]
I do not know, and this question does not belong among SAIO issues either way. 

It'd be more suitable to ask this in the X-Hax discord, of which the invite link can be found here: https://x-hax.github.io/SonicAdventureBlenderIO/contact/

With that said, I'll be closing this issue.
