### ISSUE TITLE
SA2 Importing issues

### ISSUE THREAD

**Issue by LDcode17** [X-Hax/SonicAdventureBlenderIO#33]
I was trying to make a mod called msa2 lite but when I try to import a model I get this error
![image_2024-09-08_153058282](https://github.com/user-attachments/assets/594cb507-deb7-4fda-a3a0-aa26a60d4d1f)
How do I fix this

**Comment by Justin113D** [comment]
Make sure you have NET 8.0 installed: https://x-hax.github.io/SonicAdventureBlenderIO/guides/installation/#installing-net-8

**Comment by LDcode17** [comment]
> Make sure you have NET 8.0 installed: https://x-hax.github.io/SonicAdventureBlenderIO/guides/installation/#installing-net-8

**Comment by LDcode17** [comment]
> > Make sure you have NET 8.0 installed: https://x-hax.github.io/SonicAdventureBlenderIO/guides/installation/#installing-net-8

Eyy that worked
