### ISSUE TITLE
Blender 4.2.2 Textures only visible in the shading tab and lightbox flickering

### ISSUE THREAD

**Issue by rin-ikagari** [X-Hax/SonicAdventureBlenderIO#46]
when importing the stg40 final chase textures they're only visible on the shading tab, in addition when you move the viewport it flickers,

https://github.com/user-attachments/assets/5e2f4ab2-00f6-4c7c-8b98-a68c2d6034e0

**Comment by Justin113D** [comment]
These are all expected behaviors:
1. To view textures in viewport mode, switch to texture mode
![image](https://github.com/user-attachments/assets/7e5f7cfe-d1d3-4568-9287-a0810ba9b6b1)
2. The higher you set your rendering distance, the more depth precision is lost, which will cause Z-fighting to geometry that is very close together, which causes the flickering effect you see here
